/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:3e81c023-df98-47f5-a0d9-4ed5dcb7fac6",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_l2GYA7BKq",
    "aws_user_pools_web_client_id": "4ukai259ni9bi7e4rgntqd1j11",
    "oauth": {}
};


export default awsmobile;
