/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:fa06def0-9ab7-40ad-9fb8-de190a768afe",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Edb36zhIA",
    "aws_user_pools_web_client_id": "456lun8gsn53u6drlgpv693a25",
    "oauth": {}
};


export default awsmobile;
